---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt

    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
            exclude: ^(metaphor/dbt/generated/.+)$

    - repo: https://github.com/pycqa/isort
      rev: 5.8.0
      hooks:
          - id: isort
            exclude: ^(metaphor/dbt/generated/.+)$

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy

    - repo: local
      hooks:
          - id: flakehell
            name: flakehell
            entry: flakehell lint
            language: python
            pass_filenames: false
            always_run: true

    - repo: local
      hooks:
          - id: pytest-check
            name: pytest-check
            entry: pytest
            language: system
            pass_filenames: false
            always_run: true
