---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: ^(metaphor/dbt/generated/.+)$

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^(metaphor/dbt/generated/.+)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-attrs
          - types-freezegun
          - types-requests
          - types-pytz
          - types-PyYAML

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        args: ['--skip=B101,B106,B608']

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--ignore=E203,E501,W503']

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
