# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetJobTests(BaseModel):
    job: Optional["GetJobTestsJob"]


class GetJobTestsJob(BaseModel):
    tests: List["GetJobTestsJobTests"]


class GetJobTestsJobTests(BaseModel):
    unique_id: str = Field(alias="uniqueId")
    name: Optional[str]
    status: Optional[str]
    column_name: Optional[str] = Field(alias="columnName")
    execute_completed_at: Optional[Any] = Field(alias="executeCompletedAt")
    depends_on: List[str] = Field(alias="dependsOn")


GetJobTests.model_rebuild()
GetJobTestsJob.model_rebuild()
