# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetJobModels(BaseModel):
    job: Optional["GetJobModelsJob"]


class GetJobModelsJob(BaseModel):
    models: List["GetJobModelsJobModels"]


class GetJobModelsJobModels(BaseModel):
    alias: Optional[str]
    database: Optional[str]
    name: Optional[str]
    schema_: Optional[str] = Field(alias="schema")
    unique_id: str = Field(alias="uniqueId")


GetJobModels.model_rebuild()
GetJobModelsJob.model_rebuild()
