---
version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2021-11-03T03-36-36Z # We use this version as it supports mounting existing folders into the container and using fs as the object storage.
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ../../tests/s3/data:/data # Just use test data
    command: server /data --console-address ":9001"
    container_name: minio
    restart: unless-stopped
