---
name: CI

env:
  PYTHON_VERSION: 3.7
  POETRY_VERSION: 1.2.2

# Run this build workflow for every new PR
on:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  check-py:
    name: Check Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Lint & Type Check
        run: |
          poetry install -E all
          poetry run flake8
          poetry run black --check .
          poetry run isort --check .
          poetry run mypy .
          poetry run bandit -r . -c pyproject.toml

      - name: Test
        run: |
          poetry run pytest --cov-report coverage.xml

      - name: Pytest coverage comment
        uses: orgoro/coverage@v3
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

